apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    example-webhook-enabled: "true"
spec:
  containers:
  - name: nginx
    image: quay.io/jitesoft/nginx:latest
  - name: nginx2
    image: public.ecr.aws/nginx/nginx:stable
